import React, { useState, useEffect, useContext } from "react";
import Head from "next/head";
import Link from "next/link";
import Slider from "react-slick";
import { Modal, Col, Container, Row, Button } from "react-bootstrap";
import Image from "next/image";
import apiPath from "@/utils/pathObj";
import { apiGet } from "@/utils/apiFetch";
import CategoryList from "./category/CategoryList";
import SubscriptionList from "./subscription/Subscription";
import { isEmpty } from "lodash";
import AuthContext from "@/context/AuthContext";
import { useRouter } from "next/router";
import { GoArrowRight } from "react-icons/go";
import Helpers from "@/utils/helpers";

export default function Home() {
  const homebanner = {
    dots: false,
    infinite: true,
    slidesToShow: 1,
    speed: 500,
    nextArrow: (
      <div>
        <Image width={0} height={0} src="/images/right_arrow.png" alt="" />
      </div>
    ),
    prevArrow: (
      <div>
        <Image width={0} height={0} src="/images/left_arrow.png"  alt="" />
      </div>
    ),
    responsive: [
      {
        breakpoint: 575,
        settings: {
          arrows: false,
          autoplay: true,
          autoplaySpeed: 2000,
        },
      },
    ],
  };
  const router = useRouter();
  const [banner, setBanner] = useState([]);
  const [taskNotification, setTaskNotification] = useState([]);
  const { user } = useContext(AuthContext);
  const [open, setOpen] = useState(false);
  const [show, setShow] = useState(false);

  const handleClose = () => {
    setShow(false);
  };

  const getData = async () => {
    try {
      const { status, data } = await apiGet(apiPath.getBanner);
      if (status == 200) {
        if (data.success) {
          setBanner(data.results);
        }
      }
    } catch (error) { }
  };

  const employeeTaskNotification = async () => {
    try {
      const { status, data } = await apiGet(apiPath.employeeTaskNotification);
      if (status == 200) {
        if (data.success) {
          console.log("data.results?.isRead", data.results?.isRead);
          setOpen(data.results?.isRead);
          setTaskNotification(data.results);
        }
      }
    } catch (error) { }
  };
  const findJobs = (e) => {
    e.preventDefault();
    const title = document.querySelector(".searchform input[type='text']").value;
    const location = document.querySelector(".searchform input[type='text']").value;
    if (title || location) {
      router.push({
        pathname: `/job-seeker?category=${title}`,
        query: { title, location },
      });
    } else {
      Helpers.showToast("Please enter a job title or location", "error");
    }
  }


  useEffect(() => {
    getData();
    setTimeout(() => {
      setShow(true);
    }, 100);
  }, []);
  useEffect(() => {
    if (typeof window !== "undefined" && localStorage.getItem("token")) employeeTaskNotification();
  }, []);

  return (
    <>
      <Head>
        <title>Skillmatics</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="/firebase-messaging-sw.js"></link>
        <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200;300;400;500;600;700;1000&display=swap" rel="stylesheet" ></link>
        <link type="module" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCyfi1GcGsUisGcHoaRNxTTq2VCoEXb1h8&libraries=geometry,drawing,places&callback=initMap&v=3.47"></link>
      </Head>

      {/* banner-part */}

      <section className="banner-section">
        <div className="container-fluid">
          <div className="row">
            <div
              className="col-xm-12 col-sm-12 col-md-6 col-lg-5 col-xl-5 col-xxl-5"
              style={{ padding: 0 }}
            >
              <div className="banner-left">
                <h1>FIND YOUR DREAM JOB</h1>
                <form className="searchform">
                  <Image width={0} height={0} src="/images/search-icon.png" alt="" />
                  <input type="text" placeholder="Job title, Keywords, Or Company" />
                  <div className="devider" />
                  <Image width={0} height={0} src="/images/location-icon.png" alt="" />
                  <input type="text" placeholder="City Or Postcode" />
                  <button onClick={findJobs}>Find jobs</button>
                </form>
              </div>
            </div>
            <div
              className="col-xm-12 col-sm-12 col-md-6 col-lg-7 col-xl-7 col-xxl-7"
              style={{ padding: 0 }}
            >
              <div className="banner-right">
                {/* <Image  width={0} height={0} src="img/banner-img.png" class="img-fluid" alt=""> */}
              </div>
            </div>
          </div>
        </div>
      </section>

      <div className="welcome-section">
        <div className="container">
          <div className="row">
            <div className="col-xm-12 col-sm-12 col-md-6 col-lg-6 col-xl-6 col-xxl-6">
              <div className="welcome-left">
                <Image width={0} height={0}
                  src="/images/welcome-img.png"
                  className="img-fluid"
                  alt="welcome-image"
                />
              </div>
            </div>
            <div className="col-xm-12 col-sm-12 col-md-6 col-lg-6 col-xl-6 col-xxl-6">
              <div className="welcome-right">
                <h2>
                  Welcome to <span>Empivo</span>{" "}
                </h2>
                <p>
                  Your Comprehensive HR Solution! Discover the power of Empivo - the
                  ultimate solution for transforming your HR operations with ease.
                  Dive into a world where every aspect of workforce management is
                  seamlessly integrated into one cohesive platform. From tracking
                  applicants to optimizing schedules, from managing tasks to keeping
                  precise time and attendance records, Empivo has thought of
                  everything. Experience the convenience of centralized workforce
                  management and unlock new levels of efficiency for your business.
                  With Empivo, you will never have to worry about scattered systems
                  or disjointed processes again. Join the Empivo family today and
                  elevate your HR game to new heights.{" "}
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
      {/* welcome to employe section End here  */}
      {/* features job section start here  */}
      <div className="feature-job" id="categories">
        <div className="jobs-head">
          <h2>
            FEATURED <span>JOBS</span>
          </h2>
          <p>Know your worth and find the job that qualify your life</p>
        </div>
        <div className="container">
          <div className="row">
            <div className="col-xm-12 col-sm-12 col-md-6 col-lg-6 col-xl-6 col-xxl-6">
              <div className="jobs">
                <div className="jobs-left">
                  <Image width={0} height={0} src="/images/code.png" className="img-fluid" alt="code-image" />
                </div>
                <div className="jobs-right">
                  <div className="jobtitle">
                    <p>Software Engineer (Android), Libraries </p>
                    <i className="fa-regular fa-font-awesome" />
                  </div>
                  <div className="assts">
                    <Image width={0} height={0} src="/images/business.png" alt="" />
                    <span className="Segment">Segment</span>
                    <Image width={0} height={0} src="/images/location.png" alt="" />
                    <span className="London">London, UK</span>
                    <Image width={0} height={0} src="/images/clock.png" alt="" />
                    <span className="hours">11 hours ago</span>
                    <Image width={0} height={0} src="/images/money.png" alt="" />
                    <span className="dolar">$35k-$45k</span>
                  </div>
                  <p className="span-btn">
                    {" "}
                    <a href="">
                      <span className="fulltime">Full Time</span>
                    </a>{" "}
                    <a href="">
                      <span className="private">Private</span>
                    </a>{" "}
                    <a href="">
                      <span className="urgent">Urgent</span>
                    </a>{" "}
                  </p>
                </div>
              </div>
            </div>
            <div className="col-xm-12 col-sm-12 col-md-6 col-lg-6 col-xl-6 col-xxl-6">
              <div className="jobs">
                <div className="jobs-left">
                  <Image width={0} height={0} src="/images/human.png" className="img-fluid" alt="code-image" />
                </div>
                <div className="jobs-right">
                  <div className="jobtitle">
                    <p>Recruiting Coordinator </p>
                    <i className="fa-regular fa-font-awesome one" />
                  </div>
                  <div className="assts">
                    <Image width={0} height={0} src="/images/business.png" alt="" />
                    <span className="Segment">Catalyst</span>
                    <Image width={0} height={0} src="/images/location.png" alt="" />
                    <span className="London">London, UK</span>
                    <Image width={0} height={0} src="/images/clock.png" alt="" />
                    <span className="hours">11 hours ago</span>
                    <Image width={0} height={0} src="/images/money.png" alt="" />
                    <span className="dolar">$35k-$45k</span>
                  </div>
                  <p className="span-btn">
                    {" "}
                    <a href="">
                      <span className="fulltime">Full Time</span>
                    </a>{" "}
                    <a href="">
                      <span className="private">Private</span>
                    </a>{" "}
                    <a href="">
                      <span className="urgent">Urgent</span>
                    </a>{" "}
                  </p>
                </div>
              </div>
            </div>
            <div className="col-xm-12 col-sm-12 col-md-6 col-lg-6 col-xl-6 col-xxl-6">
              <div className="jobs">
                <div className="jobs-left">
                  <Image
                    width={0} height={0}
                    src="/images/linkedin.png"
                    className="img-fluid linkedin"
                    alt="code-image"
                  />
                </div>
                <div className="jobs-right">
                  <div className="jobtitle">
                    <p>Product Manager, Studio </p>
                    <i className="fa-regular fa-font-awesome two" />
                  </div>
                  <div className="assts">
                    <Image width={0} height={0} src="/images/business.png" alt="" />
                    <span className="Segment">Invision</span>
                    <Image width={0} height={0} src="/images/location.png" alt="" />
                    <span className="London">London, UK</span>
                    <Image width={0} height={0} src="/images/clock.png" alt="" />
                    <span className="hours">11 hours ago</span>
                    <Image width={0} height={0} src="/images/money.png" alt="" />
                    <span className="dolar">$35k-$45k</span>
                  </div>
                  <p className="span-btn">
                    {" "}
                    <a href="">
                      <span className="fulltime">Full Time</span>
                    </a>{" "}
                    <a href="">
                      <span className="private">Private</span>
                    </a>{" "}
                    <a href="">
                      <span className="urgent">Urgent</span>
                    </a>{" "}
                  </p>
                </div>
              </div>
            </div>
            <div className="col-xm-12 col-sm-12 col-md-6 col-lg-6 col-xl-6 col-xxl-6">
              <div className="jobs">
                <div className="jobs-left">
                  <Image
                    width={0}
                    height={0}
                    src="/images/upwork.png"
                    className="img-fluid "
                    alt="code-image"
                  />
                </div>
                <div className="jobs-right">
                  <div className="jobtitle">
                    <p>Senior Product Designer</p>{" "}
                    <i className="fa-regular fa-font-awesome three" />
                  </div>
                  <div className="assts">
                    <Image width={0} height={0} src="/images/business.png" alt="" />
                    <span className="Segment">Upwork</span>
                    <Image width={0} height={0} src="/images/location.png" alt="" />
                    <span className="London">London, UK</span>
                    <Image width={0} height={0} src="/images/clock.png" alt="" />
                    <span className="hours">11 hours ago</span>
                    <Image width={0} height={0} src="/images/money.png" alt="" />
                    <span className="dolar">$35k-$45k</span>
                  </div>
                  <p className="span-btn">
                    {" "}
                    <a href="">
                      <span className="fulltime">Full Time</span>
                    </a>{" "}
                    <a href="">
                      <span className="private">Private</span>
                    </a>{" "}
                    <a href="">
                      <span className="urgent">Urgent</span>
                    </a>{" "}
                  </p>
                </div>
              </div>
            </div>
            <div className="col-xm-12 col-sm-12 col-md-6 col-lg-6 col-xl-6 col-xxl-6">
              <div className="jobs">
                <div className="jobs-left">
                  <Image width={0} height={0} src="/images/m.png" className="img-fluid" alt="code-image" />
                </div>
                <div className="jobs-right">
                  <div className="jobtitle">
                    <p>Senior Full Stack Engineer, Creator Success </p>
                    <i className="fa-regular fa-font-awesome four" />
                  </div>
                  <div className="assts">
                    <Image width={0} height={0} src="/images/business.png" alt="" />
                    <span className="Segment">Medium</span>
                    <Image width={0} height={0} src="/images/location.png" alt="" />
                    <span className="London">London, UK</span>
                    <Image width={0} height={0} src="/images/clock.png" alt="" />
                    <span className="hours">11 hours ago</span>
                    <Image width={0} height={0} src="/images/money.png" alt="" />
                    <span className="dolar">$35k-$45k</span>
                  </div>
                  <p className="span-btn">
                    {" "}
                    <a href="">
                      <span className="fulltime">Full Time</span>
                    </a>{" "}
                    <a href="">
                      <span className="private">Private</span>
                    </a>{" "}
                    <a href="">
                      <span className="urgent">Urgent</span>
                    </a>{" "}
                  </p>
                </div>
              </div>
            </div>
            <div className="col-xm-12 col-sm-12 col-md-6 col-lg-6 col-xl-6 col-xxl-6">
              <div className="jobs">
                <div className="jobs-left">
                  <Image width={0} height={0} src="/images/figma.png" className="img-fluid" alt="code-image" />
                </div>
                <div className="jobs-right">
                  <div className="jobtitle">
                    <p>Software Engineer (Android), Libraries</p>
                    <i className="fa-regular fa-font-awesome five" />
                  </div>
                  <div className="assts">
                    <Image width={0} height={0} src="/images/business.png" alt="" />
                    <span className="Segment">Figma</span>
                    <Image width={0} height={0} src="/images/location.png" alt="" />
                    <span className="London">London, UK</span>
                    <Image width={0} height={0} src="/images/clock.png" alt="" />
                    <span className="hours">11 hours ago</span>
                    <Image width={0} height={0} src="/images/money.png" alt="" />
                    <span className="dolar">$35k-$45k</span>
                  </div>
                  <p className="span-btn">
                    {" "}
                    <a href="">
                      <span className="fulltime">Full Time</span>
                    </a>{" "}
                    <a href="">
                      <span className="private">Private</span>
                    </a>{" "}
                    <a href="">
                      <span className="urgent">Urgent</span>
                    </a>{" "}
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      {/* features job section End here  */}
      <div className="how-work">
        <div className="container-fluid">
          <div className="row">
            <div className="col-xm-12 col-sm-12 col-md-6 col-lg-4 col-xl-4 col-xxl-4" style={{ padding: 0, background: "#F05A28" }}>
              <div className="work-left">
                <h2>How It <span>Works?</span></h2>
                <p>
                  Empivo revolutionizes HR management by offering a simple, yet
                  powerful approach to streamline your operations. Here's how it
                  works:
                </p>
              </div>
            </div>
            <div className="col-xm-12 col-sm-12 col-md-6 col-lg-8 col-xl-8 col-xxl-8 swiper-bg">
              <Slider
                dots={true}
                infinite={true}
                speed={500}
                slidesToShow={2}
                slidesToScroll={2}
                autoplay={true}
                autoplaySpeed={3000}
              >
                {[
                  {
                    img: "/images/Vector-mind.png",
                    title: "Intuitive Interface",
                    text: "Empivo's user-friendly interface makes it easy for your team to navigate and utilize its features effectively. From HR managers to employees, everyone can quickly adapt to the platform, minimizing training time and maximizing productivity."
                  },
                  {
                    img: "/images/seamless.png",
                    title: "Seamless Integration",
                    text: "Upon joining Empivo, you'll gain access to a comprehensive platform where every aspect of HR is seamlessly integrated. No more jumping between multiple systems. Empivo consolidates all your HR processes into one intuitive interface."
                  },
                  {
                    img: "/images/Group.png",
                    title: "Customized Setup",
                    text: "Our team works closely with yours to tailor Empivo to your specific needs. Whether you're a small startup or a large enterprise, we ensure that the platform is configured to align with your unique workflows and objectives."
                  }
                ].map((item, index) => (
                  <div className="item" key={index}>
                    <div className="img">
                      <Image
                        width={100}
                        height={100}
                        src={item.img}
                        className="img-fluid"
                        alt={item.title}
                        style={{ width: 'auto', height: 'auto' }}
                      />
                    </div>
                    <div className="swipe">
                      <h4>{item.title}</h4>
                      <p>{item.text}</p>
                    </div>
                  </div>
                ))}
              </Slider>
              <p className="exp-para">
                Experience the convenience of centralized workforce management
                with Empivo and unlock new levels of efficiency for your
                business. Join the Empivo family today and elevate your HR game
                to new heights.
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* Subscription Section */}
      <div className="subcribtion" id="subscription">
        <div className="sub-heading">
          <h2>
            SUBSCRIPTION&nbsp;<span>PLANS</span>
          </h2>
          <p>
            Empivo offers flexible subscription plans tailored to meet the diverse
            needs of businesses of all sizes. Whether you're a small startup, a
            growing mid-sized company, or a large enterprise, we have a plan that
            fits your requirements and budget. Choose the plan that best suits your
            organization's needs
          </p>
        </div>
        <div className="container">
          <div className="row">
            {[
              {
                name: "Feb subscription",
                price: "$50",
                duration: "15 Days",
                employees: 1,
                hrs: 1,
                accountants: 1,
                description:
                  "Pariatur Quia cum enim aut quam rerum duis in aut autem"
              },
              {
                name: "Monthly Company",
                price: "$200",
                duration: "30 Days",
                employees: 5,
                hrs: 2,
                accountants: 2,
                description:
                  "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam..."
              },
              {
                name: "Zachary Kim",
                price: "$350",
                duration: "30 Days",
                employees: 781,
                hrs: 738,
                accountants: 160,
                description:
                  "Dolorem expedita illo ut esse nobis excepturi in voluptate doloremque sint magni id nostrud illo officia assumenda irure atque"
              }
            ].map((plan, index) => (
              <div
                className="col-xm-12 col-sm-12 col-md-6 col-lg-4 col-xl-4 col-xxl-4"
                key={index}
              >
                <div className="sub-name-main">
                  <div className="sub-name-1">
                    <p>{plan.name}</p>
                  </div>
                </div>
                <div className="sub-price-main">
                  <div className="sub-price-1">
                    <p>
                      <span>{plan.price} </span> {plan.duration}
                    </p>
                  </div>
                </div>
                <div className="sub-detail">
                  <p>
                    Number of Employees <span>{plan.employees}</span>
                  </p>
                  <p>
                    Number of HRs <span>{plan.hrs}</span>
                  </p>
                  <p>
                    Number of Accountants <span>{plan.accountants}</span>
                  </p>
                  <p>{plan.description}</p>
                  <button>Get Started</button>
                </div>
              </div>
            ))}
          </div>
          <div className="view-btn">
            <Link href="/subscription">
            <button>View All Subscription</button>
            </Link>
            <p>
              Choose the plan that aligns with your organization's size, goals, and
              budget, and unlock the full potential of Empivo's comprehensive HR
              solution. Upgrade or downgrade your plan at any time to adapt to your
              evolving needs. Empivo is committed to helping you succeed by
              providing flexible, scalable, and cost-effective subscription options.
            </p>
          </div>
        </div>
      </div>

      {/* Software Platform Section */}
      <div className="software">
        <div className="software-head">
          <h3>EMPIVO IS AN EFFORTLESS ONBOARDING</h3>
          <h2>SOFTWARE PLATFORM</h2>
        </div>
        <div className="container-fluid">
          <div className="row">
            <div className="col-xm-12 col-sm-12 col-md-6 col-lg-7 col-xl-7 col-xxl-7 p-0">
              <div className="software-left">
                <Image width={0} height={0}
                  src="/images/laptop.png"
                  className="img-fluid"
                  alt="Laptop"
                />
              </div>
            </div>
            <div className="col-xm-12 col-sm-12 col-md-6 col-lg-5 col-xl-5 col-xxl-5">
              <div className="software-right">
                <p>
                  Empivo is more than just a software platform; it's your partner in
                  transforming HR operations with unparalleled ease and efficiency.
                  Say goodbye to the days of juggling multiple systems and disjointed
                  processes. With Empivo, you'll experience a seamless integration of
                  every aspect of workforce management, all within one cohesive
                  platform.
                </p>
                <div className="nextpagebutton">
                  <Link href="/empivo-feature">Product feature page</Link>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
