import React, { useState, useEffect, useContext } from "react";
import Head from "next/head";
import Slider from "react-slick";
import { Modal, Col, Container, Row, Button } from "react-bootstrap";
import Image from "next/image";
import apiPath from "@/utils/pathObj";
import { apiGet } from "@/utils/apiFetch";
import CategoryList from "./category/CategoryList";
import SubscriptionList from "./subscription/Subscription";
import { isEmpty } from "lodash";
import AuthContext from "@/context/AuthContext";
import { useRouter } from "next/router";
import { GoArrowRight } from "react-icons/go";
import Helpers from "@/utils/helpers";

export default function Home() {
  const homebanner = {
    dots: false,
    infinite: true,
    slidesToShow: 1,
    speed: 500,
    nextArrow: (
      <div>
        <Image src="/images/right_arrow.png" width={19} height={14} alt="" />
      </div>
    ),
    prevArrow: (
      <div>
        <Image src="/images/left_arrow.png" width={19} height={14} alt="" />
      </div>
    ),
    responsive: [
      {
        breakpoint: 575,
        settings: {
          arrows: false,
          autoplay: true,
          autoplaySpeed: 2000,
        },
      },
    ],
  };
  const router = useRouter();
  const [banner, setBanner] = useState([]);
  const [taskNotification, setTaskNotification] = useState([]);
  const { user } = useContext(AuthContext);
  const [open, setOpen] = useState(false);
  const [show, setShow] = useState(false);

  const handleClose = () => {
    setShow(false);
  };

  const getData = async () => {
    try {
      const { status, data } = await apiGet(apiPath.getBanner);
      if (status == 200) {
        if (data.success) {
          setBanner(data.results);
        }
      }
    } catch (error) {}
  };

  const employeeTaskNotification = async () => {
    try {
      const { status, data } = await apiGet(apiPath.employeeTaskNotification);
      if (status == 200) {
        if (data.success) {
          console.log("data.results?.isRead", data.results?.isRead);
          setOpen(data.results?.isRead);
          setTaskNotification(data.results);
        }
      }
    } catch (error) {}
  };

  useEffect(() => {
    getData();
    setTimeout(() => {
      setShow(true);
    }, 100);
  }, []);
  useEffect(() => {
    if (typeof window !== "undefined" && localStorage.getItem("token")) employeeTaskNotification();
  }, []);

  return (
    <>
      <Head>
        <title>Skillmatics</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="/firebase-messaging-sw.js"></link>
        <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200;300;400;500;600;700;1000&display=swap" rel="stylesheet"></link>
        <link type="module" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCyfi1GcGsUisGcHoaRNxTTq2VCoEXb1h8&libraries=geometry,drawing,places&callback=initMap&v=3.47"></link>
      </Head>

      {/* banner-part */}

      <section className="banner_part position-relative ">
        <Slider {...homebanner} className="">
          {banner?.length > 0 ? (
            banner?.map((res, index) => {
              return (
                <div key={index} className="banner_item">
                  <figure className="banner-fig">
                    <img style={{ width: "100%", objectFit: "cover" }} src={res?.bannerImage || ""} className="h-100" />
                  </figure>
                </div>
              );
            })
          ) : (
            <div className="banner_item">
              <figure>
                <img src="/images/banner2.jpg" />
              </figure>
            </div>
          )}
        </Slider>
      </section>

      <section className="welcome-sec">
        <Container>
          <div className="section_head text-center" id="categories">
            <h2 className="text-black text-xl ">
              Welcome to <span className="text-orange">Empivo</span>
            </h2>
            <p>
              Your Comprehensive HR Solution! Discover the power of Empivo - the ultimate solution for transforming your HR operations with ease. Dive into a world where every aspect of workforce management is seamlessly integrated into one cohesive
              platform. From tracking applicants to optimizing schedules, from managing tasks to keeping precise time and attendance records, Empivo has thought of everything. Experience the convenience of centralized workforce management and unlock
              new levels of efficiency for your business. With Empivo, you will never have to worry about scattered systems or disjointed processes again. Join the Empivo family today and elevate your HR game to new heights.
            </p>
          </div>
        </Container>
      </section>

      {/* job-categoery */}

      <section className="job-categoery">
        <Container>
          <div className="section_head text-center mb-3 mb-md-5" id="categories">
            <h2 className="text-black text-xl ">
              Jobs <span className="text-orange">Categories</span>
            </h2>
            <p>Explore diverse job opportunities across various industries.</p>
          </div>

          <div className="job_categoery_link">
            <CategoryList />
          </div>
        </Container>
      </section>

      {/* how_it_work */}
      {Helpers.andCondition(
        isEmpty(user),
        <>
          <section className="how_it_work">
            <Container>
              <div className="section_head text-center mb-3 mb-md-5">
                <h2 className="text-black text-xl ">
                  How It <span className="text-orange">Works?</span>
                </h2>
                <p>Empivo revolutionizes HR management by offering a simple, yet powerful approach to streamline your operations. Here&#39;s how it works:</p>
              </div>

              <Row className="pt-2 pt-md-4 justify-content-center">
                <Col lg={3} md={4}>
                  <div className="how_it_work_cols text-center">
                    <figure>
                      <span className="process_number">01</span>
                      <Image src="/images/Seamless Integration.png" width={84} height={84} alt=""></Image>
                    </figure>
                    <figcaption>
                      <h4 className="text-dark">Seamless Integration</h4>
                      <p className="text-sm">
                        Upon joining Empivo, you&#39;ll gain access to a comprehensive platform where every aspect of HR is seamlessly integrated. No more jumping between multiple systems or dealing with data silos. Empivo consolidates all your HR
                        processes into one intuitive interface.
                      </p>
                    </figcaption>
                  </div>
                </Col>

                <Col lg={3} md={4} className="mb-3">
                  <div className="how_it_work_cols text-center">
                    <figure>
                      <span className="process_number">02</span>
                      <Image src="/images/Customized Setup.png" width={84} height={84} alt=""></Image>
                    </figure>
                    <figcaption>
                      <h4 className="text-dark">Customized Setup</h4>
                      <p className="text-sm">
                        Our team works closely with yours to tailor Empivo to your specific needs. Whether you&#39;re a small startup or a large enterprise, we ensure that the platform is configured to align with your unique workflows and objectives.
                      </p>
                    </figcaption>
                  </div>
                </Col>

                <Col lg={3} md={4} className="mb-3">
                  <div className="how_it_work_cols text-center">
                    <figure>
                      <span className="process_number">03</span>
                      <Image src="/images/Intuitive Interface.png" width={84} height={84} alt=""></Image>
                    </figure>
                    <figcaption>
                      <h4 className="text-dark">Intuitive Interface</h4>
                      <p className="text-sm">
                        Empivo&#39;s user-friendly interface makes it easy for your team to navigate and utilize its features effectively. From HR managers to employees, everyone can quickly adapt to the platform, minimizing training time and
                        maximizing productivity.
                      </p>
                    </figcaption>
                  </div>
                </Col>
                <Col lg={3} md={4} className="mb-3">
                  <div className="how_it_work_cols text-center">
                    <figure>
                      <span className="process_number">04</span>
                      <Image src="/images/Automated Processes.png" width={84} height={84} alt=""></Image>
                    </figure>
                    <figcaption>
                      <h4 className="text-dark">Automated Processes</h4>
                      <p className="text-sm">Empivo automates repetitive tasks, saving you time and reducing the risk of errors. From onboarding new hires to processing payroll, our platform handles it all with efficiency and accuracy.</p>
                    </figcaption>
                  </div>
                </Col>
                <Col md={4} className="mb-3">
                  <div className="how_it_work_cols text-center">
                    <figure>
                      <span className="process_number">05</span>
                      <Image src="/images/Real-time Insights.png" width={84} height={84} alt=""></Image>
                    </figure>
                    <figcaption>
                      <h4 className="text-dark">Real-time Insights</h4>
                      <p className="text-sm">
                        Gain valuable insights into your workforce with Empivo&#39;s robust reporting and analytics capabilities. Monitor key HR metrics, track trends, and make data-driven decisions to optimize your operations and drive strategic
                        growth.
                      </p>
                    </figcaption>
                  </div>
                </Col>
                <Col md={4} className="mb-3">
                  <div className="how_it_work_cols text-center">
                    <figure>
                      <span className="process_number">06</span>
                      <Image src="/images/Continuous Support.png" width={84} height={84} alt=""></Image>
                    </figure>
                    <figcaption>
                      <h4 className="text-dark">Continuous Support</h4>
                      <p className="text-sm">Our dedicated support team is here to assist you every step of the way. Whether you have questions about using the platform or need technical assistance, we&#39;re always just a click or call away.</p>
                    </figcaption>
                  </div>
                </Col>
                <Col md={4} className="mb-3">
                  <div className="how_it_work_cols text-center">
                    <figure>
                      <span className="process_number">07</span>
                      <Image src="/images/Scalable Solution.png" width={84} height={84} alt=""></Image>
                    </figure>
                    <figcaption>
                      <h4 className="text-dark">Scalable Solution</h4>
                      <p className="text-sm">As your business grows, Empivo grows with you. Our platform is designed to scale seamlessly, accommodating your evolving needs and expanding workforce without compromising performance or functionality.</p>
                    </figcaption>
                  </div>
                </Col>
                <p className="text-center mt-4`">
                  Experience the convenience of centralized workforce management with Empivo and unlock new levels of efficiency for your business. Join the Empivo family today and elevate your HR game to new heights.
                </p>
              </Row>
            </Container>
          </section>
          <section className="subscription">
            <Container>
              <div className="section_head text-center mb-3 mb-md-5" id="subscription">
                <h2 className="text-black text-xl ">
                  Subscription <span className="text-orange">Plans</span>
                </h2>
                <p>
                  Empivo offers flexible subscription plans tailored to meet the diverse needs of businesses of all sizes. Whether you&#39;re a small startup, a growing mid-sized company, or a large enterprise, we have a plan that fits your
                  requirements and budget. Choose the plan that best suits your organization&#39;s needs:
                </p>
              </div>
              <SubscriptionList />
              <div className="section_head text-center mb-3 mt-4 mb-md-5">
                <p>
                  Choose the plan that aligns with your organization&#39;s size, goals, and budget, and unlock the full potential of Empivo&#39;s comprehensive HR solution. Upgrade or downgrade your plan at any time to adapt to your evolving needs.
                  Empivo is committed to helping you succeed by providing flexible, scalable, and cost-effective subscription options.
                </p>
              </div>
            </Container>
          </section>

          {/* everythink_need */}
          <section className="everythink_need">
            <Container>
              <Row className="align-items-center">
                <Col lg={8} md={7}>
                  <figure className="mb-0">
                    <Image src="/images/dashboard12.png" width="819" height="547" alt="" />
                  </figure>
                </Col>
                <Col lg={4} md={5}>
                  <article className="section_head">
                    <h2 className="text-black text-xl ">
                      Empivo is an effortless onboarding
                      <span className="text-orange d-inline d-lg-block ps-1">software platform</span>
                    </h2>
                    <p className="mt-3">
                      Empivo is more than just a software platform; it&#39;s your partner in transforming HR operations with unparalleled ease and efficiency. Say goodbye to the days of juggling multiple systems and disjointed processes. With Empivo,
                      you&#39;ll experience a seamless integration of every aspect of workforce management, all within one cohesive platform.
                    </p>
                  </article>
                  <button onClick={() => router.push("/empivo-feature")} className="theme_lg_btn text-decoration-none subscription-btn d-inline-block">
                    Product feature page
                  </button>
                </Col>
              </Row>
            </Container>
          </section>
        </>
      )}
      {Helpers.ternaryCondition(
        !isEmpty(user) && taskNotification?.isRead == false && show,
        <Modal show={!open} onHide={handleClose} centered className="agent-modal">
          <Modal.Header className="d-flex justify-content-center" closeButton>
            <div className="d-flex justify-content-between w-100 me-4 align-items-center">
              <div className="d-flex flex-column">
                <span className="modal-title h4 mb-1">Task Update </span>
              </div>
            </div>
          </Modal.Header>

          <Modal.Body>
            <div className="job_listing_main">
              <div className="jobs_list border-0">
                <div className="detail_body">
                  <Row>
                    <div className="">
                      <div className="relative z-0  w-full group mb-4">
                        <span className="assign_new_task">{taskNotification?.description}</span>
                      </div>
                    </div>
                    <div className="d-flex align-items-center justify-content-center">
                      <Button type="submit" className="py-1 px-4  theme_blue_btn rounded_5" onClick={() => router.push("/assign-task-request")}>
                        Go to assign task <GoArrowRight />
                      </Button>
                    </div>
                  </Row>
                </div>
              </div>
            </div>
          </Modal.Body>
        </Modal>,
        ""
      )}
    </>
  );
}
